//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Area.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class B2DriveForPostEntities : DbContext
    {
        public B2DriveForPostEntities()
            : base("name=B2DriveForPostEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailableUserVisit> AvailableUserVisits { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<PlaceCheckInfo> PlaceCheckInfoes { get; set; }
        public virtual DbSet<PlacePhoto> PlacePhotoes { get; set; }
        public virtual DbSet<ProcessingType> ProcessingTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductRecivedDelivered> ProductRecivedDelivereds { get; set; }
        public virtual DbSet<ProductSale> ProductSales { get; set; }
        public virtual DbSet<ProductSubCategory> ProductSubCategories { get; set; }
        public virtual DbSet<RaitingQuestion> RaitingQuestions { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RentACar> RentACars { get; set; }
        public virtual DbSet<SupervisorVisitPlace> SupervisorVisitPlaces { get; set; }
        public virtual DbSet<SupervisorVisitPlaceComment> SupervisorVisitPlaceComments { get; set; }
        public virtual DbSet<SupervisorVisitPlaceInfo> SupervisorVisitPlaceInfoes { get; set; }
        public virtual DbSet<SupervisorVisitPlacePenetration> SupervisorVisitPlacePenetrations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserLogInformation> UserLogInformations { get; set; }
        public virtual DbSet<UserPassword> UserPasswords { get; set; }
        public virtual DbSet<VisitPlace> VisitPlaces { get; set; }
        public virtual DbSet<VisitPlaceCarInfo> VisitPlaceCarInfoes { get; set; }
        public virtual DbSet<VisitPlaceInfo> VisitPlaceInfoes { get; set; }
        public virtual DbSet<VisitPlaceWareHouse> VisitPlaceWareHouses { get; set; }
        public virtual DbSet<WareHouse> WareHouses { get; set; }
    }
}
