//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Area.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorVisitPlace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupervisorVisitPlace()
        {
            this.ProductRecivedDelivereds = new HashSet<ProductRecivedDelivered>();
            this.SupervisorVisitPlaceComments = new HashSet<SupervisorVisitPlaceComment>();
            this.SupervisorVisitPlaceInfoes = new HashSet<SupervisorVisitPlaceInfo>();
            this.SupervisorVisitPlacePenetrations = new HashSet<SupervisorVisitPlacePenetration>();
            this.SPPlaceDeliveryProducts = new HashSet<SPPlaceDeliveryProduct>();
        }
    
        public int ID { get; set; }
        public int VisitPlaceID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public int PlaceID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public string CheckinLatitude { get; set; }
        public string CheckinLongitude { get; set; }
        public string PlacePositiveComment { get; set; }
        public string PlaceNegativeComment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Place Place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRecivedDelivered> ProductRecivedDelivereds { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupervisorVisitPlaceComment> SupervisorVisitPlaceComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupervisorVisitPlaceInfo> SupervisorVisitPlaceInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupervisorVisitPlacePenetration> SupervisorVisitPlacePenetrations { get; set; }
        public virtual VisitPlace VisitPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPPlaceDeliveryProduct> SPPlaceDeliveryProducts { get; set; }
    }
}
